apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-music-app.fullname" . }}
  labels:
    {{- include "my-music-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000  # Expose port 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "my-music-app.selectorLabels" . | nindent 4 }}

